### ISSUE TITLE
Question on Thesis

### ISSUE THREAD

**Issue by georgep93** [gunter1994/Video-Summarization-with-Superframe-Segmentation#1]
Hi, I read your code but I have some questions. I tried searching your thesis on google in order to clarify some points but I didn't find anything. Is there any link that you could provide the thesis, perhaps? I'm working on a similar project for my PhD thesis and I'm kinda new with the superframes. Thanks in advance!

**Comment by gunter1994** [comment]
Hi,

I made that project for an undergrad thesis, so I didn't actually publish
the work. My version of superframe segmentation was a simplified version of
the work here https://gyglim.github.io/me/vsum/index.html. This has example
code as well as the paper link.

Hope that helps. Otherwise if you have questions about my implementation I
can help you with that.

Regards,
Hunter
